<script>
	import PageList from '$lib/Components/Header/pageList.svelte';
</script>

<svelte:head>
	<title>Explore the latest fashion from StoreKit</title>
</svelte:head>

<h1 class="font-semibold text-9xl text-center my-8">Home page</h1>

<PageList />

<p>
	Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, ipsa deserunt magni dignissimos aliquam necessitatibus cupiditate voluptas ab, rem officiis earum nesciunt sed laboriosam labore suscipit veniam beatae ipsam animi minus vel quas consectetur voluptatum quam iure. Nostrum totam quasi minus nobis ipsam sapiente consectetur minima inventore. Quis velit beatae recusandae saepe architecto deleniti, perspiciatis, maiores minima iste tempore culpa ipsa. Aspernatur est officiis soluta et. Quis asperiores consequuntur ea! Maiores eius debitis molestiae explicabo? Nemo ullam reiciendis temporibus soluta, doloribus eum quisquam error impedit obcaecati at, molestias rerum consequuntur! Corporis inventore soluta ad cupiditate consequatur ipsam aspernatur culpa aut sunt nostrum. Sequi, unde?
	Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, ipsa deserunt magni dignissimos aliquam necessitatibus cupiditate voluptas ab, rem officiis earum nesciunt sed laboriosam labore suscipit veniam beatae ipsam animi minus vel quas consectetur voluptatum quam iure. Nostrum totam quasi minus nobis ipsam sapiente consectetur minima inventore. Quis velit beatae recusandae saepe architecto deleniti, perspiciatis, maiores minima iste tempore culpa ipsa. Aspernatur est officiis soluta et. Quis asperiores consequuntur ea! Maiores eius debitis molestiae explicabo? Nemo ullam reiciendis temporibus soluta, doloribus eum quisquam error impedit obcaecati at, molestias rerum consequuntur! Corporis inventore soluta ad cupiditate consequatur ipsam aspernatur culpa aut sunt nostrum. Sequi, unde?
	Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, ipsa deserunt magni dignissimos aliquam necessitatibus cupiditate voluptas ab, rem officiis earum nesciunt sed laboriosam labore suscipit veniam beatae ipsam animi minus vel quas consectetur voluptatum quam iure. Nostrum totam quasi minus nobis ipsam sapiente consectetur minima inventore. Quis velit beatae recusandae saepe architecto deleniti, perspiciatis, maiores minima iste tempore culpa ipsa. Aspernatur est officiis soluta et. Quis asperiores consequuntur ea! Maiores eius debitis molestiae explicabo? Nemo ullam reiciendis temporibus soluta, doloribus eum quisquam error impedit obcaecati at, molestias rerum consequuntur! Corporis inventore soluta ad cupiditate consequatur ipsam aspernatur culpa aut sunt nostrum. Sequi, unde?
	Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, ipsa deserunt magni dignissimos aliquam necessitatibus cupiditate voluptas ab, rem officiis earum nesciunt sed laboriosam labore suscipit veniam beatae ipsam animi minus vel quas consectetur voluptatum quam iure. Nostrum totam quasi minus nobis ipsam sapiente consectetur minima inventore. Quis velit beatae recusandae saepe architecto deleniti, perspiciatis, maiores minima iste tempore culpa ipsa. Aspernatur est officiis soluta et. Quis asperiores consequuntur ea! Maiores eius debitis molestiae explicabo? Nemo ullam reiciendis temporibus soluta, doloribus eum quisquam error impedit obcaecati at, molestias rerum consequuntur! Corporis inventore soluta ad cupiditate consequatur ipsam aspernatur culpa aut sunt nostrum. Sequi, unde?
	Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, ipsa deserunt magni dignissimos aliquam necessitatibus cupiditate voluptas ab, rem officiis earum nesciunt sed laboriosam labore suscipit veniam beatae ipsam animi minus vel quas consectetur voluptatum quam iure. Nostrum totam quasi minus nobis ipsam sapiente consectetur minima inventore. Quis velit beatae recusandae saepe architecto deleniti, perspiciatis, maiores minima iste tempore culpa ipsa. Aspernatur est officiis soluta et. Quis asperiores consequuntur ea! Maiores eius debitis molestiae explicabo? Nemo ullam reiciendis temporibus soluta, doloribus eum quisquam error impedit obcaecati at, molestias rerum consequuntur! Corporis inventore soluta ad cupiditate consequatur ipsam aspernatur culpa aut sunt nostrum. Sequi, unde?
	Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, ipsa deserunt magni dignissimos aliquam necessitatibus cupiditate voluptas ab, rem officiis earum nesciunt sed laboriosam labore suscipit veniam beatae ipsam animi minus vel quas consectetur voluptatum quam iure. Nostrum totam quasi minus nobis ipsam sapiente consectetur minima inventore. Quis velit beatae recusandae saepe architecto deleniti, perspiciatis, maiores minima iste tempore culpa ipsa. Aspernatur est officiis soluta et. Quis asperiores consequuntur ea! Maiores eius debitis molestiae explicabo? Nemo ullam reiciendis temporibus soluta, doloribus eum quisquam error impedit obcaecati at, molestias rerum consequuntur! Corporis inventore soluta ad cupiditate consequatur ipsam aspernatur culpa aut sunt nostrum. Sequi, unde?
	Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, ipsa deserunt magni dignissimos aliquam necessitatibus cupiditate voluptas ab, rem officiis earum nesciunt sed laboriosam labore suscipit veniam beatae ipsam animi minus vel quas consectetur voluptatum quam iure. Nostrum totam quasi minus nobis ipsam sapiente consectetur minima inventore. Quis velit beatae recusandae saepe architecto deleniti, perspiciatis, maiores minima iste tempore culpa ipsa. Aspernatur est officiis soluta et. Quis asperiores consequuntur ea! Maiores eius debitis molestiae explicabo? Nemo ullam reiciendis temporibus soluta, doloribus eum quisquam error impedit obcaecati at, molestias rerum consequuntur! Corporis inventore soluta ad cupiditate consequatur ipsam aspernatur culpa aut sunt nostrum. Sequi, unde?
	Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, ipsa deserunt magni dignissimos aliquam necessitatibus cupiditate voluptas ab, rem officiis earum nesciunt sed laboriosam labore suscipit veniam beatae ipsam animi minus vel quas consectetur voluptatum quam iure. Nostrum totam quasi minus nobis ipsam sapiente consectetur minima inventore. Quis velit beatae recusandae saepe architecto deleniti, perspiciatis, maiores minima iste tempore culpa ipsa. Aspernatur est officiis soluta et. Quis asperiores consequuntur ea! Maiores eius debitis molestiae explicabo? Nemo ullam reiciendis temporibus soluta, doloribus eum quisquam error impedit obcaecati at, molestias rerum consequuntur! Corporis inventore soluta ad cupiditate consequatur ipsam aspernatur culpa aut sunt nostrum. Sequi, unde?
	Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, ipsa deserunt magni dignissimos aliquam necessitatibus cupiditate voluptas ab, rem officiis earum nesciunt sed laboriosam labore suscipit veniam beatae ipsam animi minus vel quas consectetur voluptatum quam iure. Nostrum totam quasi minus nobis ipsam sapiente consectetur minima inventore. Quis velit beatae recusandae saepe architecto deleniti, perspiciatis, maiores minima iste tempore culpa ipsa. Aspernatur est officiis soluta et. Quis asperiores consequuntur ea! Maiores eius debitis molestiae explicabo? Nemo ullam reiciendis temporibus soluta, doloribus eum quisquam error impedit obcaecati at, molestias rerum consequuntur! Corporis inventore soluta ad cupiditate consequatur ipsam aspernatur culpa aut sunt nostrum. Sequi, unde?
	Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, ipsa deserunt magni dignissimos aliquam necessitatibus cupiditate voluptas ab, rem officiis earum nesciunt sed laboriosam labore suscipit veniam beatae ipsam animi minus vel quas consectetur voluptatum quam iure. Nostrum totam quasi minus nobis ipsam sapiente consectetur minima inventore. Quis velit beatae recusandae saepe architecto deleniti, perspiciatis, maiores minima iste tempore culpa ipsa. Aspernatur est officiis soluta et. Quis asperiores consequuntur ea! Maiores eius debitis molestiae explicabo? Nemo ullam reiciendis temporibus soluta, doloribus eum quisquam error impedit obcaecati at, molestias rerum consequuntur! Corporis inventore soluta ad cupiditate consequatur ipsam aspernatur culpa aut sunt nostrum. Sequi, unde?
	Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, ipsa deserunt magni dignissimos aliquam necessitatibus cupiditate voluptas ab, rem officiis earum nesciunt sed laboriosam labore suscipit veniam beatae ipsam animi minus vel quas consectetur voluptatum quam iure. Nostrum totam quasi minus nobis ipsam sapiente consectetur minima inventore. Quis velit beatae recusandae saepe architecto deleniti, perspiciatis, maiores minima iste tempore culpa ipsa. Aspernatur est officiis soluta et. Quis asperiores consequuntur ea! Maiores eius debitis molestiae explicabo? Nemo ullam reiciendis temporibus soluta, doloribus eum quisquam error impedit obcaecati at, molestias rerum consequuntur! Corporis inventore soluta ad cupiditate consequatur ipsam aspernatur culpa aut sunt nostrum. Sequi, unde?
	Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, ipsa deserunt magni dignissimos aliquam necessitatibus cupiditate voluptas ab, rem officiis earum nesciunt sed laboriosam labore suscipit veniam beatae ipsam animi minus vel quas consectetur voluptatum quam iure. Nostrum totam quasi minus nobis ipsam sapiente consectetur minima inventore. Quis velit beatae recusandae saepe architecto deleniti, perspiciatis, maiores minima iste tempore culpa ipsa. Aspernatur est officiis soluta et. Quis asperiores consequuntur ea! Maiores eius debitis molestiae explicabo? Nemo ullam reiciendis temporibus soluta, doloribus eum quisquam error impedit obcaecati at, molestias rerum consequuntur! Corporis inventore soluta ad cupiditate consequatur ipsam aspernatur culpa aut sunt nostrum. Sequi, unde?
	Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, ipsa deserunt magni dignissimos aliquam necessitatibus cupiditate voluptas ab, rem officiis earum nesciunt sed laboriosam labore suscipit veniam beatae ipsam animi minus vel quas consectetur voluptatum quam iure. Nostrum totam quasi minus nobis ipsam sapiente consectetur minima inventore. Quis velit beatae recusandae saepe architecto deleniti, perspiciatis, maiores minima iste tempore culpa ipsa. Aspernatur est officiis soluta et. Quis asperiores consequuntur ea! Maiores eius debitis molestiae explicabo? Nemo ullam reiciendis temporibus soluta, doloribus eum quisquam error impedit obcaecati at, molestias rerum consequuntur! Corporis inventore soluta ad cupiditate consequatur ipsam aspernatur culpa aut sunt nostrum. Sequi, unde?
	Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, ipsa deserunt magni dignissimos aliquam necessitatibus cupiditate voluptas ab, rem officiis earum nesciunt sed laboriosam labore suscipit veniam beatae ipsam animi minus vel quas consectetur voluptatum quam iure. Nostrum totam quasi minus nobis ipsam sapiente consectetur minima inventore. Quis velit beatae recusandae saepe architecto deleniti, perspiciatis, maiores minima iste tempore culpa ipsa. Aspernatur est officiis soluta et. Quis asperiores consequuntur ea! Maiores eius debitis molestiae explicabo? Nemo ullam reiciendis temporibus soluta, doloribus eum quisquam error impedit obcaecati at, molestias rerum consequuntur! Corporis inventore soluta ad cupiditate consequatur ipsam aspernatur culpa aut sunt nostrum. Sequi, unde?
</p>