<script lang="ts">
	import { fade } from 'svelte/transition';
	import { preloadImage } from '$lib/Functions/preloadImage';
	import { language as languageStore } from '$lib/Stores/language';
	import type { Product } from '$lib/Types/Data/product.types';
	import ColorVariation from './colorVariation.svelte';
	export let product: Product;
	const productInStock = product.stock_status === 'instock';
	let productColors: string[] = [];
	product.attributes.forEach((attribute) => {
		if (attribute.name.match(/color/i)) {
			// console.log(attribute.options);
			productColors = attribute.options;
		}
	});
</script>

{#await preloadImage(product.images[0].src)}
	<div
		class="w-full h-full aspect-[2/3] bg-base-300 animate-pulse rounded-lg border border-gray-100"
	/>
{:then base64}
	<div
		in:fade={{ duration: 500 }}
		class="group w-full bg-base-200 relative rounded-lg flex flex-col overflow-hidden shadow-lg border border-gray-100"
	>
		<a sveltekit:prefetch href="/product/{product.slug}" class="w-full h-full relative">
			<img
				class="object-cover w-full h-full {productInStock || 'opacity-40'}"
				src={base64}
				alt={product.images[0].alt}
			/>
			{#if productInStock}
				<img
					class="object-cover w-full h-full absolute inset-0 opacity-0 group-hover:opacity-100 duration-200"
					src={product.images[1].src}
					alt={product.images[1].alt}
				/>
			{/if}
		</a>
		{#if product.on_sale && productInStock}
			<div
				class="absolute bg-red-500 text-white select-none px-2 py-1 top-0 {$languageStore === 'en'
					? 'right-0 rounded-tr-lg rounded-bl-lg'
					: 'left-0 rounded-tl-lg rounded-br-lg'}"
			>
				Sale
			</div>
		{/if}
		{#if !productInStock}
			<a href="/product/{product.slug}">
				<div class="absolute inset-0 w-full h-full flex items-center justify-center select-none">
					<div class="w-full h-20 flex items-center justify-center backdrop-blur-xl">
						<h1
							class="text-4xl uppercase bg-clip-text text-transparent bg-gradient-to-br from-red-600 to-orange-800 border-t-4 border-b-4 border-red-500  font-black"
						>
							Out of stock
						</h1>
					</div>
				</div>
			</a>
		{/if}
		<div class="p-2 flex justify-between">
			<h3 class="font-bold text-sm truncate w-full">
				<a href="/product/{product.slug}" title={product.name}>
					{product.name}
				</a>
			</h3>
		</div>
		{#if productInStock}
			<div class="flex justify-between items-center">
				<div class="flex ml-3">
					{#each productColors as productColor}
						<ColorVariation colorName={productColor} />
					{/each}
				</div>
				<p class="text-md font-semibold flex justify-end m-2">
					<style>
						/*
							I had to write this in plain CSS 
							because postCSS complains about missing `del` tag
							which is not visible ofc, but it does exist in `product.price_html`
						*/
						del {
							display: flex;
							justify-items: center;
							font-size: 10px;
							color: gray;
							margin: auto 4px;
						}
					</style>
					<!-- This is auto generated by Woocommerce, so no worries about XSS -->
					{@html product.price_html}
				</p>
			</div>
		{:else}
			<div class="flex justify-between items-center">
				<div class="flex ml-3" />
				<p class="text-md font-semibold flex justify-end m-2">&#917536;</p>
			</div>
		{/if}
	</div>
{/await}
